stages:
  - "test"
  - "build"

unit_tests:
  stage: "test"
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - "docker"
  script:
    - dotnet test ./dotnet/wa-app.Tests/ --logger:"junit;LogFilePath=../artifacts/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - "./**/*test-result.xml"
    reports:
      junit:
        - "./**/*test-result.xml"
  only:
    - merge_request

solution_build:
  stage: "build"
  needs:
    - unit_tests
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - "docker"
  script:
    - dotnet publish ./dotnet/wa-app/ $DOTNET_CLI_OPTIONS
  variables: 
    DOTNET_CLI_OPTIONS: '-c ${BUILD_TYPE}'
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "./dotnet/wa-app/bin/${BUILD_TYPE}/net5.0/publish/*"
  only:
  - merge_request

build_python:
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: "build"
  needs:
    - unit_tests
  tags:
    - "docker"
  image: docker
#  image: python:3
#  image: docker:dind
  before_script:
#    - python -v
    - docker version
  script:
#    - ls  && python3 python/time.py
    - cd dotnet && docker build --build-arg API_VERSION=1.1.${CI_PIPELINE_ID} --build-arg BUILD_NUMBER=${CI_PIPELINE_ID} --tag wa-app:v1.1.${CI_PIPELINE_ID}-${CI_PIPELINE_ID}-${CI_COMMIT_SHA} .
  
  only:
  - merge_request
  